{
 "title": "Cluster / Namespaces performance",
 "description": "This dashboard provides a comprehensive view of performance and resource usage across the namespaces of a Kubernetes cluster. It includes detailed metrics on CPU and memory usage for each namespace and pod, along with an analysis of RAM usage in bytes and its percentage relative to the total cluster resources. Additionally, it displays network transmission and reception metrics for each namespace, facilitating data traffic monitoring.",
 "tags": [
  "edunext",
  "Namespaces"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   { "name": "resolution", "query": "1m, 3m, 5m" }
  ]
 },
 "panels": [
  {
   "title": "Total Cluster Namespaces",
   "type": "stat",
   "description": "This panel displays the total number of namespaces currently present in the Kubernetes cluster.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_namespace_created)" }
   ]
  },
  {
   "title": "Total Cluster Namespaces over time",
   "type": "timeseries",
   "description": "This panel shows the trend of the total number of namespaces in the Kubernetes cluster over time.",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 0 },
   "targets": [
    { "expr": "count(kube_namespace_created)", "legendFormat": "All namespaces" }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Namespace(s) usage on total cluster CPU in %",
   "type": "gauge",
   "description": "This panel represents the percentage of total cluster CPU usage attributed to the selected namespace(s).",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", image!=\"\"}[$__rate_interval])) / sum(machine_cpu_cores)"
    }
   ]
  },
  {
   "title": "CPU Usage by namespace Stacked (Vs. total cluster resources)",
   "type": "timeseries",
   "description": "This panel illustrates the CPU usage for each namespace in the cluster, displayed as a stacked time series relative to the total cluster CPU resources.",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", image!=\"\"}[$resolution])) by (namespace)/ scalar(sum(rate(node_cpu_seconds_total[$resolution])))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Namespace(s) CPU Usage in cores",
   "type": "stat",
   "description": "This panel displays the total CPU usage in cores for the selected namespace(s), along with the requested CPU, limits, and total CPU resources available in the cluster.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\"}[$resolution]))",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", resource=\"cpu\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", resource=\"cpu\"})",
     "legendFormat": "Limits"
    },
    { "expr": "sum(machine_cpu_cores)", "legendFormat": "Cluster Total" }
   ]
  },
  {
   "title": "CPU Usage by Namespaces on Cores",
   "type": "timeseries",
   "description": "This panel shows the CPU usage for each namespace in the cluster, measured in cores, over time.",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", image!=\"\"}[$resolution])) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage per Pod",
   "type": "timeseries",
   "description": "This panel displays the CPU usage per pod in the Kubernetes cluster, measured in cores, over time.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "label_replace(\n  sum by (namespace, pod) (\n    rate(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", container!=\"\"}[$resolution])\n  ), \n  \"pod\", \n  \"$1 $2\", \n  \"pod\", \n  \"(.*)\"\n)",
     "legendFormat": "{{pod}} - {{namespace}}"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Namespace(s) usage on total cluster RAM in %",
   "type": "gauge",
   "description": "This panel represents the percentage of total cluster RAM usage attributed to the selected namespace(s).",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=~\"$namespace\", container!=\"\", image!=\"\"}) / scalar(sum(machine_memory_bytes))"
    }
   ]
  },
  {
   "title": "Memory usage by namespace",
   "type": "bargauge",
   "description": "This panel provides a bar gauge visualization of memory usage for each namespace. It shows the working set memory used by containers, with a color scale from green to red based on the set thresholds.",
   "gridPos": { "h": 14, "w": 6, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", image!=\"\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory usage by namespace Stacked (Vs. total cluster resources)",
   "type": "timeseries",
   "description": "This panel displays a stacked time series graph of memory usage for each namespace compared to total cluster memory resources. The graph shows the working set memory used by containers within each namespace as a percentage of the total cluster memory. ",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=~\"$namespace\", container!=\"\", image!=\"\"}) by (namespace)/scalar(sum(machine_memory_bytes))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Namespace(s) RAM Usage in bytes",
   "type": "stat",
   "description": "This panel shows the total RAM usage in bytes for the selected namespace(s), along with the requested RAM, limits, and total RAM available in the cluster.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\"})",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", resource=\"memory\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", resource=\"memory\"})",
     "legendFormat": "Limits"
    },
    { "expr": "sum(machine_memory_bytes)", "legendFormat": "Cluster Total" }
   ]
  },
  {
   "title": "Memory usage by namespace on bytes",
   "type": "timeseries",
   "description": "This panel shows a time series graph of memory usage for each namespace in bytes. The graph uses a smooth line interpolation with a fill opacity to illustrate the memory consumption of containers within each namespace.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=~\"$namespace\", container!=\"\", image!=\"\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Pod",
   "type": "timeseries",
   "description": "This panel presents a time series graph of memory usage for each pod, displayed in bytes. It includes data on the working set memory used by containers within each pod, segmented by namespace.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(\n  sum by (namespace, pod, container) (\n    container_memory_working_set_bytes{\n      job=\"kubelet\", \n      metrics_path=\"/metrics/cadvisor\", \n      namespace=~\"$namespace\", \n      container!=\"\", \n      image!=\"\"\n    }\n  ), \n  \"container\", \n  \"$1 $2\", \n  \"container\", \n  \"(.*)\"\n)",
     "legendFormat": "{{pod}} - {{namespace}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Kubernetes Resource Count",
   "type": "timeseries",
   "description": "This panel provides a comprehensive time series view of various Kubernetes resource counts. It tracks and visualizes the number of namespaces, running containers, running pods, services, endpoints, ingresses, deployments, statefulsets, daemonsets, persistent volume claims, horizontal pod autoscalers, configmaps, secrets, network policies, and nodes over time.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_namespace_labels{namespace=~\"$namespace\"})",
     "legendFormat": "Namespaces"
    },
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\"})",
     "legendFormat": "Running Containers"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\", namespace=~\"$namespace\" })",
     "legendFormat": "Running Pods"
    },
    {
     "expr": "sum(kube_service_info{namespace=~\"$namespace\"})",
     "legendFormat": "Services"
    },
    {
     "expr": "sum(kube_endpoint_info{namespace=~\"$namespace\"})",
     "legendFormat": "Endpoints"
    },
    {
     "expr": "sum(kube_ingress_info{namespace=~\"$namespace\"})",
     "legendFormat": "Ingresses"
    },
    {
     "expr": "sum(kube_deployment_labels{namespace=~\"$namespace\"})",
     "legendFormat": "Deployments"
    },
    {
     "expr": "sum(kube_statefulset_labels{namespace=~\"$namespace\"})",
     "legendFormat": "Statefulsets"
    },
    {
     "expr": "sum(kube_daemonset_labels{namespace=~\"$namespace\"})",
     "legendFormat": "Daemonsets"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_info{namespace=~\"$namespace\"})",
     "legendFormat": "Persistent Volume Claims"
    },
    {
     "expr": "sum(kube_hpa_labels{namespace=~\"$namespace\"})",
     "legendFormat": "Horizontal Pod Autoscalers"
    },
    {
     "expr": "sum(kube_configmap_info{namespace=~\"$namespace\"})",
     "legendFormat": "Configmaps"
    },
    {
     "expr": "sum(kube_secret_info{namespace=~\"$namespace\"})",
     "legendFormat": "Secrets"
    },
    {
     "expr": "sum(kube_networkpolicy_labels{namespace=~\"$namespace\"})",
     "legendFormat": "Network Policies"
    },
    {
     "expr": "count(count by (node) (kube_node_info{namespace=~\"$namespace\"}))",
     "legendFormat": "Nodes"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Persistent Volumes - Usage in %",
   "type": "timeseries",
   "description": "This panel visualizes the usage percentage of persistent volumes in a Kubernetes cluster. It displays the ratio of used bytes to total capacity for each persistent volume claim (PVC) over time. The color scheme and threshold settings highlight high usage, with values above 80% turning red.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{namespace=~\"$namespace\"}) by (persistentvolumeclaim) \n/ \nsum(kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\"}) by (persistentvolumeclaim)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Persistent Volumes - Usage in GB",
   "type": "table",
   "description": "This panel is a table displaying persistent volume usage in your Kubernetes cluster. It features two columns for each Persistent Volume Claim (PVC): \"Used,\" indicating the total storage used in bytes, and \"Total,\" showing the total capacity in bytes.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{namespace=~\"$namespace\"}) by (persistentvolumeclaim)"
    },
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\"}) by (persistentvolumeclaim)"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Network transmit",
   "type": "timeseries",
   "description": "This panel displays a time series graph of network transmit rates for each namespace in bytes per second (Bps). It visualizes the rate at which data is transmitted over the network from containers within the specified namespaces.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{namespace=~\"$namespace\"}[$resolution])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Network receive",
   "type": "timeseries",
   "description": "This panel displays a time series graph of network receive rates for each namespace in bytes per second (Bps). It tracks how much data is being received over the network by containers within the specified namespaces.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"$namespace\"}[$resolution])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}