{
 "title": "Cluster / Nodes performance",
 "description": "This dashboard offers a comprehensive view of system performance across nodes, focusing on key metrics like CPU utilization, memory usage, storage capacity, and network traffic. It visualizes CPU usage both at the node level and for the entire cluster, tracks memory consumption relative to available memory, and displays storage usage percentages. Additionally, it provides insights into network traffic by showing the total amount of data received and transmitted by each node. The overall design aims to deliver a clear and unified perspective on resource utilization and system health.",
 "tags": [
  "edunext",
  "Nodes"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "resolution", "query": "1m, 3m, 5m" }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "stat",
   "description": "This panel displays the total count of Kubernetes nodes in the cluster.",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by (node) (kube_node_info))"
    }
   ]
  },
  {
   "title": "Cluster nodes over time",
   "type": "timeseries",
   "description": "This panel shows the time series data representing the total count of Kubernetes nodes in the cluster.",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "count(count by (node) (kube_node_info))",
     "legendFormat": "All nodes"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Utilization by node",
   "type": "timeseries",
   "description": "This panel displays the time series data for CPU utilization across different nodes in the cluster.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(1-rate(node_cpu_seconds_total{mode=\"idle\"}[$resolution])) by (instance) / sum(rate(node_cpu_seconds_total[$resolution])) by (instance)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Stacked CPU (Vs. total cluster resources)",
   "type": "timeseries",
   "description": "This panel shows the time series data for CPU utilization of each node, stacked to display the CPU usage relative to the total cluster resources.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(1-rate(node_cpu_seconds_total{mode=\"idle\"}[$resolution])) by (instance) / scalar(sum(rate(node_cpu_seconds_total[$resolution])))",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Memory Utilization by node",
   "type": "timeseries",
   "description": "This panel displays the time series data for memory utilization across different nodes, showing how much memory is used on each node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) by (instance)",
     "legendFormat": "{{ node}}"
    }
   ]
  },
  {
   "title": "Stacked memory (Vs. total cluster resources)",
   "type": "timeseries",
   "description": "\nThis panel shows the time series data for memory utilization of each node, stacked to display memory usage relative to the total cluster resources.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) by (instance)) /scalar(sum(node_memory_MemTotal_bytes))",
     "legendFormat": "{{ node}}"
    },
    {}
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Global Storage Usage",
   "type": "timeseries",
   "description": "This panel displays the time series data for global storage usage, showing the percentage of used disk space across all nodes in the cluster.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_free_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Completed read and write operations",
   "type": "timeseries",
   "description": "This panel displays the time series data for completed read and write operations on disks across different nodes, showing both read and write rates.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "o/s" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_reads_completed_total{}[$resolution])) by (instance)",
     "legendFormat": "Read {{instance}} - {{device}}"
    },
    {
     "expr": "sum(rate(node_disk_writes_completed_total{}[1m])) by (instance)",
     "legendFormat": "Write {{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "Read - Write Bytes",
   "type": "timeseries",
   "description": "\nThis panel displays the time series data for bytes read and written on disks across different nodes, showing the rates of read and write operations.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate( node_disk_read_bytes_total[$resolution])) by (instance)",
     "legendFormat": "Read {{instance}}"
    },
    {
     "expr": "sum(rate( node_disk_written_bytes_total[$__rate_interval])) by (instance)",
     "legendFormat": "Write {{instance}}"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Total Network Traffic Received by node",
   "type": "timeseries",
   "description": "This panel tracks the total network traffic received by each node over time, displaying the data in bytes. The metrics are presented with a smooth line and a moderate fill opacity to visualize the volume of incoming network traffic.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[$resolution])) by (instance)",
     "legendFormat": "Received bytes in {{ instance }}"
    }
   ]
  },
  {
   "title": "Total Network Traffic Transmitted by node",
   "type": "timeseries",
   "description": "This panel displays the total network traffic transmitted by each node over time, measured in bytes. It uses a smooth line style with a moderate fill opacity to visualize the outgoing network traffic. The data is aggregated per node, providing insight into the volume of data being transmitted.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total[$resolution])) by (instance)",
     "legendFormat": "Transmitted bytes in {{ instance }}"
    }
   ]
  }
 ]
}