{
 "title": "Celery Monitoring",
 "description": "Basic celery monitoring.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus DS", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Celery Worker Status",
   "type": "timeseries",
   "description": "This panel shows status of celery workers. 1 = online, 0 = offline.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "flower_worker_online{namespace=\"$namespace\"}",
     "legendFormat": "{{ worker }}"
    }
   ]
  },
  {
   "title": "Number of Tasks Currently Executing at Worker",
   "type": "timeseries",
   "description": "This panel shows number of tasks currently executing at worker.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "flower_worker_number_of_currently_executing_tasks{namespace=\"$namespace\"}",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  {
   "title": "Queue length by task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(task) (flower_events_total{namespace=\"$namespace\", type=\"task-sent\"}) - sum by(task) (flower_events_total{namespace=\"$namespace\", type=\"task-received\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (flower_events_total{namespace=\"$namespace\", type=\"task-sent\"}) - sum (flower_events_total{namespace=\"$namespace\", type=\"task-received\"})",
     "legendFormat": "Queue length"
    }
   ]
  },
  {
   "title": "Average Task Runtime at Worker",
   "type": "timeseries",
   "description": "This panel shows average task runtime at worker by worker and task name.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(flower_task_runtime_seconds_sum{namespace=\"$namespace\"}[5m]) / rate(flower_task_runtime_seconds_count{namespace=\"$namespace\"}[5m])",
     "legendFormat": "{{task}}, {{worker}}"
    }
   ]
  },
  {
   "title": "Task Prefetch Time at Worker",
   "type": "timeseries",
   "description": "This panel shows task prefetch time at worker by worker and task name.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "flower_task_prefetch_time_seconds{namespace=\"$namespace\"}",
     "legendFormat": "{{task}}, {{worker}}"
    }
   ]
  },
  {
   "title": "Number of Tasks Prefetched At Worker",
   "type": "timeseries",
   "description": "This panel shows number of tasks prefetched at worker by task and worker name.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "flower_worker_prefetched_tasks{namespace=\"$namespace\"}",
     "legendFormat": "{{task}}, {{worker}}"
    }
   ]
  },
  {
   "title": "Task Success Ratio",
   "type": "timeseries",
   "description": "This panel presents average task success ratio over time by task name.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(avg_over_time(flower_events_total{type=\"task-succeeded\", namespace=\"$namespace\"}[15m])) by (task)  / sum(avg_over_time(flower_events_total{type=~\"task-failed|task-succeeded\", namespace=\"$namespace\"}[15m])) by (task)) * 100",
     "legendFormat": "{{ task }}"
    }
   ]
  },
  {
   "title": "Task Failure Ratio",
   "type": "timeseries",
   "description": "This panel presents average task failure ratio over time by task name.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(avg_over_time(flower_events_total{type=\"task-failed\", namespace=\"$namespace\"}[15m])) by (task) / sum(avg_over_time(flower_events_total{type=~\"task-failed|task-succeeded\", namespace=\"$namespace\"}[15m])) by (task)) * 100",
     "legendFormat": "{{ task }}"
    }
   ]
  }
 ]
}