{
 "title": "Cluster / Installations performance",
 "description": "This dashboard provides an overview of various metrics related to instalations in the cluster. It includes panels displaying memory and cpu usage by deployment, available and unavailable replicas, pod states, and ingress request volumes. The information is presented through various visualization types such as time series graphs and tables, offering insights into the current state and trends of deployments and resource utilization.",
 "tags": [
  "edunext",
  "Installations"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "resolution", "query": "1m, 3m, 5m" }
  ]
 },
 "panels": [
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage Total",
   "type": "gauge",
   "description": "\nThis panel displays the total CPU usage as a percentage for different deployments within a selected namespace. It uses a gauge visualization to represent the proportion of CPU utilization, with color-coded thresholds indicating low, moderate, and high usage levels.",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$Namespace\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$Namespace\", workload_type=~\"deployment|statefulset|daemonset|job|cronjob\"}\n)/scalar(sum(rate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "{{$Deployment}}"
    }
   ]
  },
  {
   "title": "CPU Usage by Deployment  (Vs. total cluster resources)",
   "type": "timeseries",
   "description": "This panel visualizes CPU usage by different deployments in a selected namespace, compared to the total cluster CPU resources. It uses a time series graph to display the CPU consumption of each deployment, showing how individual deployments' usage trends relate to the overall cluster resource usage.",
   "gridPos": { "h": 13, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$Namespace\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$Namespace\", workload_type=~\"deployment|statefulset|daemonset|job|cronjob\"}\n) by (workload, workload_type)/scalar(sum(rate(node_cpu_seconds_total[$resolution])))\n",
     "legendFormat": "{{workload}} - {{workload_type}}"
    }
   ]
  },
  {
   "title": "CPU Usage by Deployment  on Cores",
   "type": "timeseries",
   "description": "This panel shows the CPU usage in cores for different deployments within a selected namespace. It uses a time series graph to display the CPU consumption by each deployment, providing insights into how CPU resources are utilized across different deployment types over time.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{namespace=\"$Namespace\"}[$resolution])\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$Namespace\", workload_type=~\"deployment|statefulset|daemonset|job|cronjob\"}\n) by (workload, workload_type)",
     "legendFormat": "{{workload}} - {{workload_type}}"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Memory Usage Total",
   "type": "gauge",
   "description": "This panel displays the total memory usage as a percentage for different deployments within a selected namespace. It uses a gauge visualization to show how much memory is being consumed relative to the total available memory, with color-coded thresholds indicating low, moderate, and high usage levels.",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=~\"$Namespace\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"$Namespace\", workload_type=~\"deployment|statefulset|daemonset|job|cronjob\"}\n)/scalar(sum(machine_memory_bytes))"
    }
   ]
  },
  {
   "title": "Memory Usage by Deployment  (Vs. total cluster resources)",
   "type": "timeseries",
   "description": "This panel illustrates the memory usage of various deployments within a selected namespace, compared to the total cluster memory resources. It uses a time series graph to track how each deployment's memory consumption evolves over time relative to the overall cluster memory usage.",
   "gridPos": { "h": 13, "w": 18, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=~\"$Namespace\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"$Namespace\", workload_type=~\"deployment|statefulset|daemonset|job|cronjob\"}\n) by (workload, workload_type)/scalar(sum(machine_memory_bytes))\n",
     "legendFormat": "{{workload}} - {{workload_type}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Deployment  on Bytes",
   "type": "timeseries",
   "description": "This panel displays the memory usage in bytes for various deployments within a selected namespace. It uses a time series graph to track the amount of memory consumed by each deployment over time, providing insights into how memory usage trends differ across deployment types.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=~\"$Namespace\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"$Namespace\", workload_type=~\"deployment|statefulset|daemonset|job|cronjob\"}\n) by (workload, workload_type)\n",
     "legendFormat": "{{workload}} - {{workload_type}}"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Pods state",
   "type": "bargauge",
   "description": "\nThis panel shows the current state of pods within a selected namespace, using a bar gauge to represent the proportion of pods in different phases (e.g., running, pending, failed). The gauge provides a visual summary of the distribution of pod states, with color coding to indicate different phases and thresholds highlighting the relative proportions of each state.",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{namespace=~\"$Namespace\"}) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Replicas available by deployment",
   "type": "timeseries",
   "description": "This panel displays the number of available replicas for each deployment within a selected namespace. It uses a time series graph to track the availability of replicas over time for different deployments, allowing you to monitor how many replicas are currently running and how this changes over time.",
   "gridPos": { "h": 13, "w": 9, "x": 6, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "replicas" } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=\"$Namespace\"}) by (deployment)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Replicas unavailable by deployment",
   "type": "timeseries",
   "description": "This panel displays the number of unavailable replicas for each deployment within a selected namespace. It uses a time series graph to track the unavailability of replicas over time for different deployments, allowing you to monitor how many replicas are not available and how this number changes over time.",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 52 },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=\"$Namespace\"}) by (deployment)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Replicas by deployment",
   "type": "table",
   "description": "This panel provides a table view displaying the number of available and unavailable replicas for each deployment within a selected namespace. It aggregates the data by deployment, showing two key columns: \"Available\" and \"Unavailable,\" which represent the count of available and unavailable replicas, respectively.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=\"$Namespace\"}) by (deployment)",
     "legendFormat": "{{deployment}}"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=\"$Namespace\"}) by (deployment)"
    }
   ]
  },
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Ingress Request Volume by Status",
   "type": "timeseries",
   "description": "This panel visualizes the volume of ingress requests categorized by status for a selected namespace. It uses a time series graph to display the rate of requests over time, with the data aggregated by status.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=~\"$Namespace\"}[$resolution])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress Request Volume",
   "type": "timeseries",
   "description": "This panel presents the overall volume of ingress requests for a selected namespace using a time series graph. The graph displays the rate of requests over time with data aggregated for all statuses.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=~\"$Namespace\"}[$resolution]))",
     "legendFormat": "All requests"
    }
   ]
  }
 ]
}